// x86 target
// Error message numbers.
// Parallel with msgs.rc.

#define EM_usage                0
#define EM_bad_parameter        1
#define EM_eof                  2
#define EM_num2big              3
#define EM_string2big           4
#define EM_ident2big            5
#define EM_badtoken             6
#define EM_statement            7
#define EM_hexdigit             8
#define EM_badnumber            9
#define EM_exponent             10
#define EM_nosource             11
#define EM_tag                  12
#define EM_dashD                13
#define EM_error                14
#define EM_no_inline            15
#define EM_unknown_pragma       16
#define EM_bad_char             17
#define EM_rpar                 18
#define EM_prototype            19
#define EM_ident_exp            20
#define EM_preprocess           21
#define EM_memmodels            22
#define EM_ptr_handle           22
#define EM_eol                  23
#define EM_num                  24
#define EM_linnum               25
#define EM_explicit_cast        26
#define EM_2manyerrors          27
#define EM_badtag               28
#define EM_num_args             29
#define EM_filespec             30
#define EM_endif                31
#define EM_eof_endif            32
#define EM_else                 33
#define EM_macarg               34
#define EM_align                35
#define EM_undef                36
#define EM_noextern             37
#define EM_rbra                 38
#define EM_id_or_decl           39
#define EM_not_param            40
#define EM_param_context        41
#define EM_array_of_funcs       42
#define EM_return_type          43
#define EM_noprototype          44
#define EM_datadef              45
#define EM_punctuation          46
#define EM_storage_class        47
#define EM_multiple_def         48
#define EM_undefined            49
#define EM_bitfield             50
#define EM_semi_member          51
#define EM_bitwidth             52
#define EM_unknown_size         53
#define EM_bad_member_type      54
#define EM_rcur                 55
#define EM_2manyinits           56
#define EM_response_file        57
#define EM_pragma_proto         57
#define EM_lcur_exp             58
#define EM_const_init           59
#define EM_init2tmp             60
#define EM_cpp_comments         60
#define EM_decl_spec_seq        61
#define EM_colon                62
#define EM_exp                  63
#define EM_function             64
#define EM_ident_abstract       65
#define EM_lpar                 66
#define EM_while                67
#define EM_bad_break            68
#define EM_bad_continue         69
#define EM_unknown_tag          70
#define EM_unknown_label        71
#define EM_0size                72
#define EM_not_struct           73
#define EM_notamember           74
#define EM_bad_ptr_arith        75
#define EM_type_mismatch        76
#define EM_mult_default         77
#define EM_not_switch           78
#define EM_int2far              79
#define EM_mult_case            80
#define EM_redefined            81
#define EM_illegal_cast         82
#define EM_illegal_op_types     83
#define EM_open_input           84
#define EM_open_output          85
#define EM_divby0               86
#define EM_not_variable         87
#define EM_bad_filespec         88
#define EM_mult_files           89
#define EM_bad_filename         90
#define EM_nestcomment          91
#define EM_string               92
#define EM_blank_arg            93
#define EM_integral             94
#define EM_pointer              95
#define EM_array                96
#define EM_array_dim            97
#define EM_extra_semi           98
#define EM_bad_struct_use       99
#define EM_assignment           100
#define EM_lvalue               101
#define EM_valuenotused         102
#define EM_noaddress            103
#define EM_noendofstring        104
#define EM_nomatch_proto        105
#define EM_void_novalue         106
#define EM_write_error          107
#define EM_octal_digit          108
#define EM_const_assign         109
#define EM_null_nl              110
#define EM_nomem                111
#define EM_command_line_error   112
#define EM_no_comment_term      115
#define EM_warning              116
#define EM_lexical_error        117
#define EM_preprocessor_error   118
#define EM_line_format          119
#define EM_no_ident_decl        120
#define EM_typesize_gt64k       121
#define EM_0or1                 122
#define EM_unnamed_bitfield     123
#define EM_large_auto           124
#define EM_illegal_type_combo   125
#define EM_no_nl                126
#define EM_no_ret_value         127
#define EM_sizeof_bitfield      128
#define EM_decl_0size_bitfield  129
#define EM_notagname            130
#define EM_prep_exp             131
#define EM_assignthis           132
#define EM_empty_sdl            132
#define EM_bad_escape_seq       133
#define EM_binary_exp           134
#define EM_obsolete_del         135
#define EM_cseg_global          136
#define EM_far16_model          137
#define EM_far16_extern         138
#define EM_pch_config           139
#define EM_obsolete_inc         140
#define EM_cv_arg               141
#define EM_hashhash_end         142
#define EM_hashparam            143
#define EM_explicit_param       144
#define EM_ext_block_init       145
#define EM_data_in_pch          146
#define EM_comma_const          147
#define EM_const_case           148
#define EM_empty_decl           149
#define EM_used_b4_set          150
#define EM_alloca_win           151
#define EM_cseg_2big            151
#define EM_nops_expected        152
#define EM_bad_op               153
#define EM_bad_float_op         154
#define EM_bad_addr_mode        155
#define EM_opcode_exp           156
#define EM_prefix               157
#define EM_bad_operand          158
#define EM_ptr_exp              159
#define EM_386_op               160
#define EM_ret_auto             161
#define EM_seg_gt_64k           162
#define EM_bad_kwd              163
#define EM_ambig_member         164
#define EM_mem_same_type        165
#define EM_bad_iset             166
#define EM_no_longlong          167
#define EM_internal_error       168
#define EM_max_macro_text       169
#define EM_ds_ne_dgroup         170
#define EM_max_macro_params     171
#define EM_no_static_def        172
#define EM_no_ext_def           173
#define EM_null                 174
#define EM_not_a_member         175
#define EM_missing_comma        176
#define EM_implied_ret          177
#define EM_recursive_proto      177
#define EM_comma                178
#define EM_pop_wo_push          179
#define EM_pascal_str_2long     180
#define EM_bad_type_comb        181
#define EM_wrong_lang           182
#define EM_bad_ref              183
#define EM_fatal_error          184
#define EM_was_declared         185
#define EM_now_declared         186
#define EM_cant_map_file        187
#define EM_cant_reserve_mem     188
#define EM_ambig_ref            189
#define EM_2manyfiles           190
#define EM_explicitcast         191
#define EM_2manytypes           192
#define EM_nakedret             193
#define EM_nodebexp             194
#define EM_nolocale             195
#define EM_tdb                  196

// C++ errors
#define EM_musthaveinit         0
#define EM_func_anon_union      1
#define EM_no_instance          2
#define EM_not_class            3
#define EM_public_base          4
#define EM_type_complex         6
#define EM_nomatch              7
#define EM_not_overloadable     8
#define EM_opovl_function       9
#define EM_n_op_params          10
#define EM_param_class          11
#define EM_class_colcol         12
#define EM_base_class           13
#define EM_access_decl          14
#define EM_bad_ctor_dtor        15
#define EM_no_inst_member       16
#define EM_colcol_lpar          17
#define EM_conv_member          18
#define EM_ctor_context         19
#define EM_seen_init            20
#define EM_bad_mem_init         21
#define EM_vector_init          22
#define EM_del_ptrs             23
#define EM_ext_inline           24
#define EM_non_static           25
#define EM_one_arg              26
#define EM_linkage_specs        27
#define EM_not_accessible       28
#define EM_private              29
#define EM_ctor_X               30
#define EM_static_init_inside   31
#define EM_ambig_type_conv      32
#define EM_pure_virtual         33
#define EM_const_needs_init     34
#define EM_main_type            35
#define EM_no_ctor              36
#define EM_dup_direct_base      37
#define EM_static_virtual       38
#define EM_opnew_type           39
#define EM_opdel_type           40
#define EM_zero                 41
#define EM_create_abstract      42
#define EM_cant_generate        43
#define EM_not_ctor             44
#define EM_base_memmodel        45
#define EM_near2far             46
#define EM_bad_oparrow          47
#define EM_default_redef        48
#define EM_ctor_disallowed      49
#define EM_ambig_ref_base       50
#define EM_pure_func_virtual    51
#define EM_vbase                52
#define EM_union_tors           53
#define EM_ptr_member           54
#define EM_change_access        55
#define EM_cvt_private_base     56
#define EM_glbl_ambig_unions    57
#define EM_const_mem_ctor       58
#define EM_static_mem_func      59
#define EM_overload_ambig       60
#define EM_postfix_arg          61
#define EM_cv_func              62
#define EM_access_class         63
#define EM_access_diff          64
#define EM_derived_class_name   65
#define EM_decl_other_class     66
#define EM_friend_sclass        67
#define EM_friend_type          68
#define EM_tilde_class          69
#define EM_not_enum_member      70
#define EM_skip_init            71
#define EM_fwd_ref_base         72
#define EM_lt_cast              73
#define EM_gt                   74
#define EM_templ_param_lists    75
#define EM_not_class_templ      76
#define EM_bad_templ_decl       77
#define EM_templ_arg_type       78
#define EM_adel_array           79
#define EM_local_static         80
#define EM_conv_ret             81
#define EM_templ_arg_unused     82
#define EM_cant_gen_templ_inst  83
#define EM_bad_ref_init         84
#define EM_no_mem_init          85
#define EM_del_ptr_const        86

#if TX86
#define EM_colcol_exp           89
#else
#define EM_ptr_ref              97
#define EM_mult_decl            98
#endif

#define EM_exception_specs      99
#define EM_eh_types             100
#define EM_catch_masked         101
#define EM_catch_ellipsis       102
#define EM_catch_follows        103
#define EM_not_of_ambient_model 104
#define EM_compileEH            105
#define EM_typeinfo_h           106
#define EM_compileRTTI          107
#define EM_ptr_to_class         108
#define EM_not_pointer          109
#define EM_ptr_to_polymorph     110
#define EM_lt_following         111
#define EM_mix_EH               112
#define EM_no_type              113
#define EM_templ_default_args   114
#define EM_nogen_cpct           115
#define EM_mem_init_following   116
#define EM_semi_template        117
#define EM_semi_rbra            118
#define EM_null0                119
#define EM_enable_anew          120
#define EM_type_argument        121
#define EM_param_no_float       122
#define EM_diff_ret_type        123
#define EM_nspace_alias_semi    124
#define EM_nspace_name          125
#define EM_nspace_undef_id      126
#define EM_nspace_enclose       127
#define EM_using_semi           128
#define EM_using_member         129

#if TX86
#define EM_bad_leave            0
#define EM_finally_or_except    1
#define EM_try_needs_win32      2
#define EM_needs_filter         3
#define EM_needs_handler        4
#define EM_bad_declspec         5
#define EM_bad_based_type       6
#define EM_bad_dllimport        7
#define EM_before_pch           8
#define EM_pch_first            9
#define EM_thread_and_dllimport 10
#define EM_no_CV3               11
#endif

